# If you update the build.sh flags, you must also update src/blst/dune accordingly
on: [push]
jobs:
  # Not supporting clang 10
  # Getting error:
  # > ld: unsupported tapi file type '!tapi-tbd' in YAML file
  # > '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/lib/libSystem.tbd'
  # > for architecture x86_64
  # > clang: error: linker command failed with exit code 1 (use -v to see invocation)

  # blst-build-clang-10:
  #   runs-on: [macos-10.15]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         sudo xcode-select -s /Applications/Xcode_10.3.app/Contents/Developer
  #         cc --version
  #         cd src/blst/libblst && ./build.sh -shared -Wno-missing-braces

  blst-build-clang-11:
    name: Build blst on MacOS clang11
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode_11.3.app/Contents/Developer
          cc --version
          cd src/blst/libblst && ./build.sh -shared -Wno-missing-braces

  blst-build-clang-12:
    name: Build blst on MacOS clang12
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
          cc --version
          cd src/blst/libblst && ./build.sh -shared -Wno-missing-braces

  test-build:
    name: Build the whole library and run test on s390x
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: use architecture s390x
        with:
          arch: s390x
          distro: ubuntu20.04

          run: |
            uname --machine
            apt-get update -y
            apt-get install ocaml opam -y
            opam init --bare -y
            opam switch create . --no-install --packages ocaml-base-compiler.4.12.1
            eval $(opam env)
            ocaml --version
            opam --version
            opam depext -i -y conf-pkg-config conf-libffi
            opam depext -i -y zarith
            opam pin add bls12-381.dev . --no-action
            opam pin add bls12-381-unix.dev . --no-action
            opam install bls12-381 -y --with-test --deps-only
            opam install bls12-381-unix -y --with-test --deps-only
            # For benchmark repository
            opam install core_bench
            dune build
            dune build @install
            dune runtest
